version: "0.1"

subdomains:
  express-subdomain:
    module: nullstone/autogen-aws-subdomain
    dns:
      template: "express.{{ NULLSTONE_ENV }}"

apps:
  node-express-quickstart:
    module: nullstone/aws-fargate-service
    connections:
      cluster-namespace: namespace0
    vars:
      cpu: 256
      memory: 512
      port: 80
    capabilities:
      ingress:
        module: nullstone/aws-load-balancer
        connections:
          subdomain: express-subdomain
